# Generated by Django 3.2.25 on 2024-06-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240627_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(
                default='no-image-available.png', upload_to='blog'),
        ),
    ]
