# Generated by Django 3.2.25 on 2024-06-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_plantprice_size'),
        ('checkout', '0002_auto_20240611_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='products.product'),
        ),
    ]
