# Generated by Django 3.2.25 on 2024-06-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_alter_order_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_size',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
