# Generated by Django 3.2.25 on 2024-06-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_alter_orderitem_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_size',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
