# Generated by Django 3.2.25 on 2024-06-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('phone_number', models.CharField(
                    blank=True, max_length=20, null=True)),
                ('street_address1', models.CharField(
                    blank=True, max_length=80, null=True)),
                ('street_address2', models.CharField(
                    blank=True, max_length=80, null=True)),
                ('town_or_city', models.CharField(
                    blank=True, max_length=40, null=True)),
                ('county', models.CharField(
                    blank=True, max_length=80, null=True)),
                ('postcode', models.CharField(
                    blank=True, max_length=20, null=True)),
                ('country', models.CharField(
                    blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_county',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_postcode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_street_address1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_street_address2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_town_or_city',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_address',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='user_profile.address'
                ),
        ),
    ]
