# Generated by Django 3.2.25 on 2024-06-30 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0003_alter_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_address',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
