# Generated by Django 3.2.25 on 2024-05-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(
                default='default_images/no-image-available.png',
                upload_to='plant-images/'),
        ),
    ]
