# Generated by Django 3.2.25 on 2024-05-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='care_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='light_level',
        ),
        migrations.AddField(
            model_name='product',
            name='ease_of_care',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], default='moderate', max_length=9),
        ),
        migrations.AddField(
            model_name='product',
            name='light',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'Bright')], default='medium', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('tall', 'Tall')], default='medium', max_length=6),
        ),
    ]
