# Generated by Django 3.2.25 on 2024-05-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240520_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.AlterField(
            model_name='product',
            name='light',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('bright', 'Bright')], default='medium', max_length=6),
        ),
        migrations.CreateModel(
            name='PlantSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('sm', 'Small'), ('med', 'Medium'), ('lg', 'Large')], max_length=10)),
                ('height', models.CharField(max_length=20)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product')),
            ],
        ),
    ]
