# Generated by Django 3.2.25 on 2024-05-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pet_ok',
            field=models.BooleanField(default=False),
        ),
    ]
