# Generated by Django 3.2.25 on 2024-06-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20240529_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprice',
            name='size',
            field=models.CharField(choices=[('sm', 'Small'), ('med', 'Medium'), ('lg', 'Large')], max_length=10),
        ),
    ]
